### ISSUE TITLE
"priority" prop not working properly in ExportedImage

### ISSUE THREAD

**Issue by kopino4** [Niels-IO/next-image-export-optimizer#45] opened 2022-10-03 10:29 UTC
Hi @Niels-IO,

It's me again. The `ExportedImage` has worse LCP performance then the native `Image` when using `priority`.

I am performing the following Lighthouse testing in the browser:
![seetings](https://user-images.githubusercontent.com/43185020/193555753-79f22e95-cca7-43ac-a070-ba25032716ef.png)

When using `Image` without `priority`:
![ImageNoPriority](https://user-images.githubusercontent.com/43185020/193555918-5ce68190-f227-4bbe-86a7-fef25f26fed0.png)

![ImageNoPrioritySpeed](https://user-images.githubusercontent.com/43185020/193555962-69a069d4-3f42-4649-a2c4-686c8c7f5b6d.png)

When using `Image` with `priority` set:
![Image](https://user-images.githubusercontent.com/43185020/193556074-01329364-dfb3-4abc-9745-3fb5e407bf50.png)

![ImageSpeed](https://user-images.githubusercontent.com/43185020/193556117-6ec4b5d4-2427-4d81-8e93-d16db6c0106a.png)

However using `ExportedImage` with `priority` makes no difference in the LCP time:
![ExportedImage](https://user-images.githubusercontent.com/43185020/193556285-3462f9e2-d9a6-47c8-9a50-2861b314c37f.png)

![ExportedImageSpeed](https://user-images.githubusercontent.com/43185020/193556301-4c140f9d-2cba-46a2-a532-79d85ef2be89.png)

This is my next.config.js file:
![nextjs_config](https://user-images.githubusercontent.com/43185020/193556367-b1ededde-b57a-4281-99cc-3d3bb31ecf3f.png)

Even lowering the quality did not help. To me it look like the priority attribute does not get set properly,
can you take a look at this?

Thanks!

**Comment by Niels-IO** [comment] 2022-10-05 08:45
Hi @kopino4,

I think I figured it out now. Could you please test if the issue is fixed in version 0.15.0?

**Comment by kopino4** [comment] 2022-10-05 11:54
Hey @Niels-IO,

i confirm, the update to 0.15.0 helped! 

Thanks alot, keep up the great work :)

**Comment by Niels-IO** [comment] 2022-10-05 12:50
Cool, thanks again for raising the issue. Kind of hard to spot the bug as it was working in the local test environment but not with the published package.

**Closed by Niels-IO** 2022-10-05 12:50 UTC
